service: yarn-v2-lambda-example

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

custom:
  webpack:
    webpackConfig: './webpack.js'
    includeModules: false
    packager: yarn

layers:
  yarnV2TestNodeModules:
    path: ../../serverless-build

functions:
  basicHttpHandler:
    name: handle-request
    handler: src/handler.handler
    layers:
      - { Ref: YarnV2TestNodeModulesLambdaLayer }
    environment:
      # This ensures we can load PnP packages
      NODE_OPTIONS: "--require /opt/nodejs/.pnp.cjs"
    events:
      - http:
          method: get
          path: sample
