service: yarn-v2-lambda-example

plugins:
  - serverless-webpack
  - serverless-plugin-datadog

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

custom:
  webpack:
    webpackConfig: './webpack.js'
    includeModules: false
    packager: yarn
  datadog:
    forwarder: ${ssm:/lambda/datadog/dev-datadog-forwarder/arn}
    enabled: true
    addLayers: false

layers:
  yarnV2TestNodeModules:
    path: ../../serverless-build

functions:
  basicHttpHandler:
    name: handle-request
    handler: src/handler.handler
    layers:
      - { Ref: YarnV2TestNodeModulesLambdaLayer }
    events:
      - http:
          method: get
          path: sample
